spring:
  thymeleaf:
    cache: true
server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: REPETHELPER_SESSION
        secure: true
        http-only: true
        same-site: lax
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
